"""preserve analytics after flag deletion

Revision ID: 0aa538493f2d
Revises: 7c2ad0c19925
Create Date: 2026-08-29 23:27:19.578516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0aa538493f2d'
down_revision: Union[str, Sequence[str], None] = '7c2ad0c19925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluation_analytics', 'flag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_evaluation_analytics_flag_id'), table_name='evaluation_analytics')
    op.drop_constraint(op.f('uq_flag_evaluation_hour'), 'evaluation_analytics', type_='unique')
    op.drop_constraint(op.f('evaluation_analytics_flag_id_fkey'), 'evaluation_analytics', type_='foreignkey')
    op.create_foreign_key(None, 'evaluation_analytics', 'flags', ['flag_id'], ['flag_id'], ondelete='SET NULL')
    op.drop_column('evaluation_analytics', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_analytics', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'evaluation_analytics', type_='foreignkey')
    op.create_foreign_key(op.f('evaluation_analytics_flag_id_fkey'), 'evaluation_analytics', 'flags', ['flag_id'], ['flag_id'])
    op.create_unique_constraint(op.f('uq_flag_evaluation_hour'), 'evaluation_analytics', ['flag_id', 'evaluation_date', 'evaluation_hour'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_evaluation_analytics_flag_id'), 'evaluation_analytics', ['flag_id'], unique=False)
    op.alter_column('evaluation_analytics', 'flag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
