"""Update targeting_rules schema

Revision ID: 6e60c09a92d4
Revises: b8d34243b7f6
Create Date: 2026-08-04 22:26:59.231312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e60c09a92d4'
down_revision: Union[str, Sequence[str], None] = 'b8d34243b7f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targeting_rules', sa.Column('attribute', sa.String(length=100), nullable=False))
    op.add_column('targeting_rules', sa.Column('operator', sa.String(length=50), nullable=False))
    op.add_column('targeting_rules', sa.Column('value', sa.String(length=255), nullable=False))
    op.drop_column('targeting_rules', 'created_at')
    op.drop_column('targeting_rules', 'rule_type')
    op.drop_column('targeting_rules', 'enabled')
    op.drop_column('targeting_rules', 'target_value')
    op.drop_column('targeting_rules', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targeting_rules', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('targeting_rules', sa.Column('target_value', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('targeting_rules', sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('targeting_rules', sa.Column('rule_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('targeting_rules', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('targeting_rules', 'value')
    op.drop_column('targeting_rules', 'operator')
    op.drop_column('targeting_rules', 'attribute')
    # ### end Alembic commands ###
