"""add flag cleanup tracking fields

Revision ID: 6e6144540e54
Revises: e5abd6169a0c
Create Date: 2026-08-29 22:08:31.198930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6144540e54'
down_revision: Union[str, Sequence[str], None] = 'e5abd6169a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flags', sa.Column('cleanup_state', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flags', 'cleanup_state')
    # ### end Alembic commands ###
