"""cascade targeting rules when flag deleted

Revision ID: 7c2ad0c19925
Revises: b1860d2a288d
Create Date: 2026-08-29 23:26:00.525404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2ad0c19925'
down_revision: Union[str, Sequence[str], None] = 'b1860d2a288d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('targeting_rules_flag_id_fkey'), 'targeting_rules', type_='foreignkey')
    op.create_foreign_key(None, 'targeting_rules', 'flags', ['flag_id'], ['flag_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'targeting_rules', type_='foreignkey')
    op.create_foreign_key(op.f('targeting_rules_flag_id_fkey'), 'targeting_rules', 'flags', ['flag_id'], ['flag_id'])
    # ### end Alembic commands ###
