"""allow flag versions after flag deletion

Revision ID: b1860d2a288d
Revises: 3f266ca94bb2
Create Date: 2026-08-29 23:24:43.610381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1860d2a288d'
down_revision: Union[str, Sequence[str], None] = '3f266ca94bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flag_versions', 'flag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('flag_versions_flag_id_fkey'), 'flag_versions', type_='foreignkey')
    op.create_foreign_key(None, 'flag_versions', 'flags', ['flag_id'], ['flag_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flag_versions', type_='foreignkey')
    op.create_foreign_key(op.f('flag_versions_flag_id_fkey'), 'flag_versions', 'flags', ['flag_id'], ['flag_id'])
    op.alter_column('flag_versions', 'flag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
