"""add indexes to flags

Revision ID: b8d34243b7f6
Revises: ed9f9aec5705
Create Date: 2026-07-29 23:43:36.858935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d34243b7f6'
down_revision: Union[str, Sequence[str], None] = 'ed9f9aec5705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_flags_environment_id'), 'flags', ['environment_id'], unique=False)
    op.create_index(op.f('ix_flags_key'), 'flags', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flags_key'), table_name='flags')
    op.drop_index(op.f('ix_flags_environment_id'), table_name='flags')
    # ### end Alembic commands ###
