"""Create initial tables

Revision ID: ed9f9aec5705
Revises: 
Create Date: 2026-07-26 11:42:47.683546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9f9aec5705'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('environment_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_environments_environment_id'), 'environments', ['environment_id'], unique=False)
    op.create_table('user_group_memberships',
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('membership_id')
    )
    op.create_index(op.f('ix_user_group_memberships_membership_id'), 'user_group_memberships', ['membership_id'], unique=False)
    op.create_table('flags',
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('default_value', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_team', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.environment_id'], ),
    sa.PrimaryKeyConstraint('flag_id')
    )
    op.create_index(op.f('ix_flags_flag_id'), 'flags', ['flag_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.environment_id'], ),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.flag_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_logs_audit_id'), 'audit_logs', ['audit_id'], unique=False)
    op.create_table('flag_versions',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.String(length=100), nullable=True),
    sa.Column('new_value', sa.String(length=100), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.flag_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_flag_versions_version_id'), 'flag_versions', ['version_id'], unique=False)
    op.create_table('targeting_rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('target_value', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.flag_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_targeting_rules_rule_id'), 'targeting_rules', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_targeting_rules_rule_id'), table_name='targeting_rules')
    op.drop_table('targeting_rules')
    op.drop_index(op.f('ix_flag_versions_version_id'), table_name='flag_versions')
    op.drop_table('flag_versions')
    op.drop_index(op.f('ix_audit_logs_audit_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_flags_flag_id'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_user_group_memberships_membership_id'), table_name='user_group_memberships')
    op.drop_table('user_group_memberships')
    op.drop_index(op.f('ix_environments_environment_id'), table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
