"""prevent duplicate flags per environment

Revision ID: fc4cf35edb94
Revises: 2c0f51d7825b
Create Date: 2026-08-29 23:05:13.861902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4cf35edb94'
down_revision: Union[str, Sequence[str], None] = '2c0f51d7825b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_flag_key_environment', 'flags', ['key', 'environment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_flag_key_environment', 'flags', type_='unique')
    # ### end Alembic commands ###
